name: Greetings there

on: [pull_request_target, issues]

jobs:
  greeting: 
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello there, Let's continue pushing' Check with the Repo owner to confirm your changes"
        pr-message: "You just pulled this repo, be careful not to cause errors!! ' Thank you, Regards MJCappella"
